[project]
name = "rxp-task-reordering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.3.0",
    "click>=8.5.0",
    "duckdb>=1.5.5",
    "jinja2>=3.1.6",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "snowflake-connector-python[secure-local-storage]>=4.7.5",
    "sqlparse>=0.6.0",
    "statsmodels>=0.15.0",
    "vl-convert-python>=1.9.0.post1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
