WITH c AS (
  SELECT LOWER(EMPLOYEE_USER_NAME) AS AGENT, ORDER_ID, QUEUE_DISPLAY_NAME AS Q,
         LEG_HANDLED_DTTM AS T, HANDLE_TIME_SEC AS SECS, LEG_HANDLED_DTTM::DATE AS D,
         LOWER(SESSION_INITIAL_DIRECTION) AS DIR
  FROM EDLDB.BT_CUSTOMER_CARE.FCT_CONTACTS_BRD
  WHERE LEG_HANDLED_DTTM >= '2026-02-01' AND LEG_HANDLED_DTTM < '2026-08-01'
    AND HANDLE_TIME_SEC IS NOT NULL AND HANDLE_TIME_SEC > 0
    AND EMPLOYEE_USER_NAME IS NOT NULL AND ORDER_ID IS NOT NULL
    AND QUEUE_DISPLAY_NAME IS NOT NULL
), seq AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY T) AS CALL_NO,
    COUNT(*)     OVER (PARTITION BY ORDER_ID)            AS CALLS_ON_ORDER,
    COUNT(*) OVER (PARTITION BY ORDER_ID, AGENT ORDER BY T
                   ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS PRIOR_BY_SAME_AGENT,
    COUNT(*) OVER (PARTITION BY ORDER_ID, AGENT ORDER BY T
                   ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING) AS FUTURE_BY_SAME_AGENT
  FROM c
), rep AS (
  SELECT AGENT, D, Q, SECS, DIR,
         IFF(PRIOR_BY_SAME_AGENT > 0, 1, 0) AS SAME_AGENT_CONTEXT,
         IFF(FUTURE_BY_SAME_AGENT > 0, 1, 0) AS FUTURE_CONTEXT
  FROM seq WHERE CALL_NO > 1 AND CALLS_ON_ORDER >= 2
),
contrasts AS (
  SELECT AGENT, D, Q, SECS, DIR,
         'handled_before' AS ANALYSIS_CASE,
         SAME_AGENT_CONTEXT AS CONTEXT
  FROM rep

  UNION ALL

  SELECT AGENT, D, Q, SECS, DIR,
         'placebo' AS ANALYSIS_CASE,
         FUTURE_CONTEXT AS CONTEXT
  FROM rep
),
cellp AS (
  SELECT ANALYSIS_CASE, DIR, AGENT, Q, D,
         SUM(CONTEXT) AS N1, SUM(1 - CONTEXT) AS N0,
         AVG(IFF(CONTEXT = 1, SECS, NULL)) AS M1,
         AVG(IFF(CONTEXT = 0, SECS, NULL)) AS M0,
         VAR_SAMP(IFF(CONTEXT = 1, SECS, NULL)) AS S1_SQ,
         VAR_SAMP(IFF(CONTEXT = 0, SECS, NULL)) AS S0_SQ
  FROM contrasts
  GROUP BY 1, 2, 3, 4, 5
  HAVING SUM(CONTEXT) > 1
     AND SUM(1 - CONTEXT) > 1
)
SELECT ANALYSIS_CASE AS "case", DIR, COUNT(*) AS CELLS, SUM(N1 + N0) AS CALLS,
  ROUND((SUM(M1*N1)/SUM(N1)) - (SUM(M0*N0)/SUM(N0)), 3) AS POOLED_DELTA_S,
  ROUND(AVG(M1-M0), 3) AS EQUAL_WEIGHT_DELTA_S,
  ROUND(MEDIAN(M1-M0), 3) AS MEDIAN_CELL_DELTA_S,
  ROUND(SUM((N1 * N0 / (N1 + N0)) * (M1 - M0)) / SUM(N1 * N0 / (N1 + N0)), 2) AS FE_WITHIN_CELL_DELTA_S,
  SQRT(
    SUM(
      POWER(N1 * N0 / (N1 + N0), 2)
      * (S1_SQ / N1 + S0_SQ / N0)
    )
    / POWER(SUM(N1 * N0 / (N1 + N0)), 2)
  ) AS FE_WITHIN_CELL_SE_S
FROM cellp
GROUP BY ANALYSIS_CASE, DIR
ORDER BY ANALYSIS_CASE, DIR;
