WITH c AS (
  SELECT LOWER(EMPLOYEE_USER_NAME) AS AGENT, ORDER_ID, QUEUE_DISPLAY_NAME AS Q,
         LEG_HANDLED_DTTM AS T, HANDLE_TIME_SEC AS SECS, LEG_HANDLED_DTTM::DATE AS D,
         LOWER(SESSION_INITIAL_DIRECTION) AS DIR
  FROM EDLDB.BT_CUSTOMER_CARE.FCT_CONTACTS_BRD
  WHERE LEG_HANDLED_DTTM >= '2026-02-01' AND LEG_HANDLED_DTTM < '2026-08-01'
    AND HANDLE_TIME_SEC IS NOT NULL AND HANDLE_TIME_SEC > 0
    AND EMPLOYEE_USER_NAME IS NOT NULL AND ORDER_ID IS NOT NULL
    AND QUEUE_DISPLAY_NAME IS NOT NULL
), seq AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY T) AS CALL_NO,
    COUNT(*)     OVER (PARTITION BY ORDER_ID)            AS CALLS_ON_ORDER,
    COUNT(*) OVER (PARTITION BY ORDER_ID, AGENT ORDER BY T
                   ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS PRIOR_BY_SAME_AGENT,
    COUNT(*) OVER (PARTITION BY ORDER_ID, AGENT ORDER BY T
                   ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING) AS FUTURE_BY_SAME_AGENT
  FROM c
), rep AS (
  SELECT AGENT, D, Q, SECS, DIR,
         IFF(PRIOR_BY_SAME_AGENT > 0, 1, 0) AS SAME_AGENT_CONTEXT,
         IFF(FUTURE_BY_SAME_AGENT > 0, 1, 0) AS FUTURE_CONTEXT
  FROM seq WHERE CALL_NO > 1 AND CALLS_ON_ORDER >= 2
),
cellp AS (
  SELECT DIR, AGENT,Q,D,
         SUM(SAME_AGENT_CONTEXT) AS N1, SUM(1-SAME_AGENT_CONTEXT) AS N0,
         AVG(IFF(SAME_AGENT_CONTEXT=1,SECS,NULL)) AS M1,
         AVG(IFF(SAME_AGENT_CONTEXT=0,SECS,NULL)) AS M0
  FROM rep GROUP BY 1,2,3,4
  HAVING SUM(SAME_AGENT_CONTEXT) > 0 AND SUM(1-SAME_AGENT_CONTEXT) > 0
)
SELECT dir, COUNT(*) AS CELLS,  SUM(N1+N0) AS CALLS,
  ROUND((SUM(M1*N1)/SUM(N1)) - (SUM(M0*N0)/SUM(N0)), 3) AS POOLED_DELTA_S,
  ROUND(SUM((N1*N0/(N1+N0))*(M1-M0)) / SUM(N1*N0/(N1+N0)), 3) AS FE_WITHIN_CELL_DELTA_S,
  ROUND(AVG(M1-M0), 3) AS EQUAL_WEIGHT_DELTA_S,
  ROUND(MEDIAN(M1-M0), 3) AS MEDIAN_CELL_DELTA_S,
  ROUND(SQRT(VAR_SAMP(M1-M0)), 3) AS EQUAL_WEIGHT_DELTA_S_SE,
FROM cellp group by dir;
