WITH ordered AS (
  SELECT USER_ID, ITEM_COHORT, STARTED_AT, TRANSITION_STARTED_AT::DATE AS dt,
    LAG(ITEM_COHORT) OVER (PARTITION BY USER_ID, TRANSITION_STARTED_AT::DATE ORDER BY STARTED_AT) AS prev_cohort,
    DWELL_IN_PROGRESS_TO_CLOSED_MINUTES AS work_min
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TRANSITION_STARTED_AT >= '2026-08-01'
    AND TASK_TYPE = 'DUR' AND FINAL_STATUS = 'CLOSED'
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND DWELL_IN_PROGRESS_TO_CLOSED_MINUTES BETWEEN 0.01 AND 30
    AND ITEM_COHORT != 'Unknown'
)
SELECT
  CASE WHEN ITEM_COHORT = prev_cohort THEN 'Same Cohort' ELSE 'Different Cohort' END AS allocation_pattern,
  COUNT(*) AS tasks,
  ROUND(AVG(work_min), 4) AS avg_min,
  ROUND(MEDIAN(work_min), 4) AS med_min,
  ROUND(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY work_min), 4) AS p75_min
FROM ordered WHERE prev_cohort IS NOT NULL
GROUP BY allocation_pattern ORDER BY allocation_pattern;
