#!/usr/bin/env python3
"""Run one read-only Snowflake statement through DuckDB's Snowflake extension."""

from __future__ import annotations

from datetime import datetime, timezone
import re
import uuid
from pathlib import Path

import click
import sqlparse

REQUIRED_SETTINGS = ("RXP_SNOWFLAKE_ACCOUNT", "RXP_SNOWFLAKE_USER", "RXP_SNOWFLAKE_DATABASE", "RXP_SNOWFLAKE_WAREHOUSE", "RXP_SNOWFLAKE_SCHEMA")
OPTIONAL_SETTINGS = ("RXP_SNOWFLAKE_ROLE",)
SAFE_SETTING = re.compile(r"^[A-Za-z0-9_.-]+$")
SAFE_USER = re.compile(r"^[A-Za-z0-9_.@-]+$")
READ_ONLY_START = re.compile(r"^(?:SELECT|WITH|SHOW|DESCRIBE|EXPLAIN)\b", re.IGNORECASE)
MIN_DUCKDB_VERSION = (1, 5, 3)


def parse_dotenv(path: Path) -> dict[str, str]:
    """Parse simple KEY=VALUE assignments without executing .env as shell code."""
    values: dict[str, str] = {}
    allowed = set(REQUIRED_SETTINGS + OPTIONAL_SETTINGS)
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        key, separator, value = line.partition("=")
        if not separator or key not in allowed:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        if not value:
            continue
        validator = SAFE_USER if key == "RXP_SNOWFLAKE_USER" else SAFE_SETTING
        if not validator.fullmatch(value):
            raise ValueError(f"{path}:{line_number}: {key} contains unsupported characters")
        values[key] = value
    return values


def validate_statement(sql: str) -> None:
    without_comments = re.sub(r"/\*.*?\*/", "", sql, flags=re.DOTALL)
    without_comments = re.sub(r"--[^\n]*", "", without_comments).strip()
    if without_comments.endswith(";"):
        without_comments = without_comments[:-1].rstrip()
    if not without_comments or not READ_ONLY_START.match(without_comments):
        raise ValueError("SQL must begin with SELECT, WITH, SHOW, DESCRIBE, or EXPLAIN")
    if ";" in without_comments:
        raise ValueError("Only one SQL statement is allowed")


def format_sql(sql: str) -> str:
    """Format SQL for human-readable display and query-history files."""
    return sqlparse.format(
        sql.strip(),
        reindent=True,
        keyword_case="upper",
        strip_comments=False,
    ).rstrip()


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def dollar_quote(sql: str) -> str:
    tag = "rxp_query"
    while f"${tag}$" in sql:
        tag += "_x"
    return f"${tag}${sql}${tag}$"


def validate_workspace_path(path: Path, label: str) -> Path:
    if path.is_absolute():
        raise ValueError(f"{label} must be a relative path")
    workspace = Path.cwd().resolve()
    destination = (workspace / path).resolve()
    try:
        destination.relative_to(workspace)
    except ValueError as error:
        raise ValueError(f"{label} must remain inside the current repository") from error
    return destination


def validate_output_path(path: Path) -> Path:
    if path.suffix.lower() != ".parquet":
        raise ValueError("--output-parquet must end in .parquet")
    destination = validate_workspace_path(path, "--output-parquet")
    destination.parent.mkdir(parents=True, exist_ok=True)
    return destination


def record_sql(sql: str, directory: Path, source: str) -> Path:
    directory = validate_workspace_path(directory, "--sql-log-dir")
    directory.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    path = directory / f"rxp-sql-{timestamp}-{uuid.uuid4().hex[:8]}.sql"
    path.write_text(f"-- Generated by rxp-sql\n-- Source: {source}\n-- Recorded at: {timestamp}\n\n{sql.rstrip()}\n", encoding="utf-8")
    return path


def verify_duckdb() -> None:
    try:
        import duckdb
    except ImportError as error:
        raise ValueError("DuckDB is not installed; run `uv sync`") from error
    match = re.fullmatch(r"v?(\d+)\.(\d+)\.(\d+)", duckdb.__version__)
    if match is None:
        raise ValueError("could not determine the installed DuckDB version")
    installed = tuple(int(part) for part in match.groups())
    if installed < MIN_DUCKDB_VERSION:
        required = ".".join(str(part) for part in MIN_DUCKDB_VERSION)
        raise ValueError(f"DuckDB {required} or newer is required for external-browser Snowflake SSO")


@click.command()
@click.argument("query_file", required=False, type=click.Path(path_type=Path, dir_okay=False))
@click.option("--query", help="One read-only SQL statement")
@click.option("--env-file", type=click.Path(path_type=Path, dir_okay=False), default=Path(".env"), show_default=True, help="Local connection settings")
@click.option("--output-parquet", type=click.Path(path_type=Path, dir_okay=False), help="Relative output path within this repository")
@click.option("--sql-log-dir", type=click.Path(path_type=Path, file_okay=False), default=Path("generated_sql"), show_default=True, help="Relative directory for recorded SQL")
def main(query_file: Path | None, query: str | None, env_file: Path, output_parquet: Path | None, sql_log_dir: Path) -> None:
    """Run one read-only Snowflake statement through DuckDB."""
    if (query_file is None) == (query is None):
        raise click.UsageError("provide exactly one QUERY_FILE or --query")
    try:
        verify_duckdb()
    except ValueError as error:
        raise click.UsageError(str(error)) from error
    if not env_file.is_file():
        raise click.UsageError(f"environment file not found: {env_file}")
    try:
        settings = parse_dotenv(env_file)
        missing = [key for key in REQUIRED_SETTINGS if key not in settings]
        if missing:
            raise ValueError("missing required settings: " + ", ".join(missing))
        sql = query if query is not None else query_file.read_text(encoding="utf-8")
        validate_statement(sql)
        formatted_sql = format_sql(sql)
        destination = validate_output_path(output_parquet) if output_parquet else None
    except (OSError, ValueError) as error:
        raise click.UsageError(str(error)) from error

    try:
        source_name = str(query_file) if query_file else "--query"
        sql_record = record_sql(formatted_sql, sql_log_dir, source_name)
        click.echo("SQL:\n" + formatted_sql)
        click.echo(f"Recorded SQL: {sql_record.relative_to(Path.cwd().resolve())}")
    except (OSError, ValueError) as error:
        raise click.UsageError(str(error)) from error

    properties = [
        "TYPE snowflake", f"ACCOUNT {sql_literal(settings['RXP_SNOWFLAKE_ACCOUNT'])}", f"USER {sql_literal(settings['RXP_SNOWFLAKE_USER'])}",
        f"DATABASE {sql_literal(settings['RXP_SNOWFLAKE_DATABASE'])}", f"WAREHOUSE {sql_literal(settings['RXP_SNOWFLAKE_WAREHOUSE'])}",
        f"SCHEMA {sql_literal(settings['RXP_SNOWFLAKE_SCHEMA'])}", "AUTH_TYPE 'ext_browser'",
    ]
    if role := settings.get("RXP_SNOWFLAKE_ROLE"):
        properties.append(f"ROLE {sql_literal(role)}")
    remote_query = "snowflake_query(" + dollar_quote(sql) + ", 'rxp_snowflake')"
    final_statement = (
        f"COPY (SELECT * FROM {remote_query}) TO {sql_literal(str(destination))} (FORMAT PARQUET);"
        if destination
        else f"SELECT * FROM {remote_query};"
    )
    bootstrap_sql = "\n".join([
        "INSTALL snowflake FROM community;", "LOAD snowflake;",
        "CREATE SECRET rxp_snowflake (" + ", ".join(properties) + ");",
        final_statement,
    ])
    import duckdb

    connection = duckdb.connect(":memory:")
    try:
        result = connection.execute(bootstrap_sql)
        if result.description:
            click.echo("\t".join(column[0] for column in result.description))
            for row in result.fetchall():
                click.echo("\t".join("" if value is None else str(value) for value in row))
        if destination:
            click.echo(f"Wrote Parquet file: {destination.relative_to(Path.cwd().resolve())}")
    finally:
        connection.close()


if __name__ == "__main__":
    main()
