CREATE OR REPLACE TRANSIENT TABLE EDLDB_DEV.PET_HEALTH_ANALYTICS_SANDBOX.MY_RXP_RX_USAGE_TO_RX AS
SELECT
    actions.RX_USAGE_ID,
    MIN(actions.RX_ID) AS RX_ID
FROM EDLDB.BT_HCA_HCDM.RXP_RX_USAGE_ACTIONS AS actions
WHERE actions.RX_USAGE_ID IS NOT NULL
  AND actions.RX_ID IS NOT NULL
GROUP BY actions.RX_USAGE_ID;
