WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
), ded AS (
  SELECT * FROM (SELECT b.*, ROW_NUMBER() OVER
                 (PARTITION BY USER_ID, ORDER_ID ORDER BY STARTED_AT) RN
                 FROM base b) WHERE RN=1
), s AS (
  SELECT *, LAG(COH)  OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PCOH,
            LEAD(COH) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS NCOH
  FROM ded
), lk AS (
  SELECT USER_ID, D, COH, SECS,
         IFF(PCOH=COH,1,0) AS PAST_SAME, IFF(NCOH=COH,1,0) AS FUT_SAME
  FROM s WHERE PCOH IS NOT NULL AND NCOH IS NOT NULL
), cellp AS (
  SELECT USER_ID, D, COH,
         SUM(PAST_SAME) AS N1, SUM(1-PAST_SAME) AS N0,
         AVG(IFF(PAST_SAME=1,SECS,NULL)) AS M1,
         AVG(IFF(PAST_SAME=0,SECS,NULL)) AS M0
  FROM lk GROUP BY 1,2,3
  HAVING SUM(PAST_SAME) > 0 AND SUM(1-PAST_SAME) > 0
)
SELECT COUNT(*) AS CELLS, SUM(N1+N0) AS TASKS,
  ROUND((SUM(M1*N1)/SUM(N1)) - (SUM(M0*N0)/SUM(N0)), 3) AS POOLED_DELTA_S,
  ROUND(SUM((N1*N0/(N1+N0))*(M1-M0)) / SUM(N1*N0/(N1+N0)), 3) AS FE_WITHIN_CELL_DELTA_S,
  ROUND(AVG(M1-M0), 3) AS EQUAL_WEIGHT_DELTA_S,
  ROUND(MEDIAN(M1-M0), 3) AS MEDIAN_CELL_DELTA_S,
  ROUND(100.0*AVG(IFF(M1<M0,1.0,0.0)),1) AS PCT_CELLS_FAVOURING_SAME
FROM cellp
