-- Is this correct; discuss with Rohan
-- What is the total time we are supposed to have?
-- There is a PV1/DUR field in tasks. There is also Prescription Verification 1
WITH pharm AS (
  SELECT DISTINCT LOWER(EMPLOYEE_USER_NAME) AS UN
  FROM EDLDB.BT_PET_HEALTH_RX_OPERATIONS.RX_DIM_EMPLOYEES
  WHERE JOB_TITLE IN ('Pharmacist','Compounding Pharmacist','Pharmacist in Charge',
                      'Pharmacist Lead','Technical Services Pharmacist')
    AND EMPLOYEE_USER_NAME IS NOT NULL
), l AS (
  SELECT f.LABOR_FUNCTION, f.TIME_IN_SECONDS
  FROM EDLDB.BT_PET_HEALTH_RX_OPERATIONS.FCT_PERFORMANCE__LABOR_ENTRY_DAY f
  JOIN pharm p ON p.UN = LOWER(f.EMPLOYEE_ID)
  WHERE f.TIME_SEGMENT >= '2026-02-01' AND f.TIME_SEGMENT < '2026-08-01'
    AND f.TIME_IN_SECONDS > 0
    AND COALESCE(f.WH_ID,'') NOT IN ('Network','UNMAPPED')
)
SELECT LABOR_FUNCTION,
  ROUND(SUM(TIME_IN_SECONDS)/3600.0,0) AS HOURS,
  ROUND(100.0*SUM(TIME_IN_SECONDS)/SUM(SUM(TIME_IN_SECONDS)) OVER (),1) AS PCT
FROM l GROUP BY 1 ORDER BY HOURS DESC;


WITH t AS (
  SELECT l.USER_ID, l.ORDER_ID, l.PART_NUMBER, l.STARTED_AT,
         l.ITEM_COHORT AS COH, p.PRODUCT_MERCH_CLASSIFICATION3 AS CLS
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE l
  LEFT JOIN EDLDB.CHEWYBI.PRODUCTS_PHARMACY p
    ON p.CHEWY_PHARMACY_PART_NUMBER = l.PART_NUMBER
  WHERE l.TASK_TYPE='DUR'
    AND l.TASK_CREATED_AT >= '2026-02-01' AND l.TASK_CREATED_AT < '2026-08-01'
    AND l.DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND l.USER_ID IS NOT NULL AND l.STARTED_AT IS NOT NULL AND l.PART_NUMBER IS NOT NULL
    AND l.ITEM_COHORT IS NOT NULL AND p.PRODUCT_MERCH_CLASSIFICATION3 IS NOT NULL
), s AS (
  SELECT *,
    LAG(PART_NUMBER) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PP,
    LAG(ORDER_ID)    OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PO,
    LAG(COH)         OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PCOH,
    LAG(CLS)         OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PCLS
  FROM t
), fl AS (
  SELECT *, IFF(PP = PART_NUMBER,1,0) AS SAME_DRUG,
            IFF(PCOH = COH,1,0)       AS SAME_COH,
            IFF(PCLS = CLS,1,0)       AS SAME_CLS
  FROM s WHERE PP IS NOT NULL AND PO <> ORDER_ID
), obs AS (
  SELECT USER_ID, COUNT(*) AS N, AVG(SAME_DRUG) AS OBS_DRUG,
         AVG(SAME_COH) AS OBS_COH, AVG(SAME_CLS) AS OBS_CLS
  FROM fl GROUP BY 1 HAVING COUNT(*) >= 200
), mc AS (
  SELECT USER_ID, SUM(POWER(C/TOT,2)) AS EXP_COH FROM (
    SELECT USER_ID, COH, COUNT(*)::FLOAT C,
           SUM(COUNT(*)) OVER (PARTITION BY USER_ID)::FLOAT TOT
    FROM fl GROUP BY 1,2) GROUP BY 1
)
SELECT COUNT(*) AS PHARMACISTS, SUM(N) AS TASKS,
  ROUND(100.0*SUM(OBS_COH*N)/SUM(N),2) AS OBSERVED_PCT,
  ROUND(100.0*SUM(EXP_COH*N)/SUM(N),2) AS RANDOM_PCT,
  ROUND(SUM(OBS_COH*N)/SUM(EXP_COH*N),4) AS RATIO
FROM obs JOIN mc USING (USER_ID)


WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
), drugbench AS (
  SELECT PART_NUMBER, AVG(SECS) AS DRUG_MEAN FROM base GROUP BY 1
), ded AS (
  SELECT * FROM (SELECT b.*, ROW_NUMBER() OVER
                 (PARTITION BY USER_ID, ORDER_ID ORDER BY STARTED_AT) RN
                 FROM base b) WHERE RN = 1
), s AS (
  SELECT *, LAG(COH) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PCOH FROM ded
), r AS (
  SELECT *, SUM(IFF(PCOH=COH,0,1)) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT
              ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUN_ID
  FROM s
), p AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY USER_ID, RUN_ID ORDER BY STARTED_AT) AS POS,
            COUNT(*)     OVER (PARTITION BY USER_ID, RUN_ID) AS RUN_LEN
  FROM r
), g AS (
  SELECT p.USER_ID, p.D, p.COH, p.SECS, db.DRUG_MEAN,
         CASE WHEN RUN_LEN = 1 THEN '1_ISOLATED'
              WHEN POS = 1 THEN '2_RUN_START'
              WHEN POS = 2 THEN '3_POS_2'
              WHEN POS = 3 THEN '4_POS_3'
              WHEN POS BETWEEN 4 AND 6 THEN '5_POS_4_6'
              ELSE '6_POS_7PLUS' END AS GRP
  FROM p JOIN drugbench db ON db.PART_NUMBER = p.PART_NUMBER
), both AS (
  SELECT USER_ID, D, COH FROM g GROUP BY 1,2,3
  HAVING SUM(IFF(GRP='1_ISOLATED',1,0)) > 0 AND SUM(IFF(GRP<>'1_ISOLATED',1,0)) > 0
), f AS (
  SELECT g.* FROM g JOIN both b ON b.USER_ID=g.USER_ID AND b.D=g.D AND b.COH=g.COH
)
SELECT GRP, COUNT(*) AS TASKS,
  ROUND(SUM(SECS)/COUNT(*),1) AS AHT_S, MEDIAN(SECS) AS AHT_MED_S,
  ROUND(SUM(DRUG_MEAN)/COUNT(*),1) AS EXPECTED_FROM_DRUG_MIX_S,
  ROUND(SUM(SECS)/NULLIF(SUM(DRUG_MEAN),0),4) AS DRUG_ADJ_INDEX
FROM f GROUP BY 1 ORDER BY 1



 WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS BETWEEN 0 and 300
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
    AND USAGE_STATE='APPROVED'
    AND IS_REFILL = true
    AND HANDOFF_TYPE = NULL
), drugbench AS (
  SELECT PART_NUMBER, MEDIAN(SECS) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS, 0.95), MAX(SECS) AS DRUG_MAX, STDDEV(SECS) as DEVIATION, COUNT(*) as cnt FROM base GROUP BY 1
)
select d.*, p.name from  drugbench d
join edldb.pdm.product p on d.part_number = p.part_number
where cnt > 10 order by cnt desc limit 10;


    WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         LEAST(DWELL_IN_PROGRESS_TO_CLOSED_SECONDS,300) AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
), drugbench AS (
  SELECT PART_NUMBER, AVG(SECS) AS DRUG_MEAN FROM base GROUP BY 1
), ded AS (
  SELECT * FROM (SELECT b.*, ROW_NUMBER() OVER
                 (PARTITION BY USER_ID, ORDER_ID ORDER BY STARTED_AT) RN
                 FROM base b) WHERE RN = 1
), s AS (
  SELECT *, LAG(COH) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PCOH FROM ded
), r AS (
  SELECT *, SUM(IFF(PCOH=COH,0,1)) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT
              ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUN_ID
  FROM s
), p AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY USER_ID, RUN_ID ORDER BY STARTED_AT) AS POS,
            COUNT(*)     OVER (PARTITION BY USER_ID, RUN_ID) AS RUN_LEN
  FROM r
), g AS (
  SELECT p.USER_ID, p.D, p.COH, p.SECS, db.DRUG_MEAN,
         CASE WHEN RUN_LEN = 1 THEN '1_ISOLATED'
              WHEN POS = 1 THEN '2_RUN_START'
              WHEN POS = 2 THEN '3_POS_2'
              WHEN POS = 3 THEN '4_POS_3'
              WHEN POS BETWEEN 4 AND 6 THEN '5_POS_4_6'
              ELSE '6_POS_7PLUS' END AS GRP
  FROM p JOIN drugbench db ON db.PART_NUMBER = p.PART_NUMBER
), both AS (
  SELECT USER_ID, D, COH FROM g GROUP BY 1,2,3
  HAVING SUM(IFF(GRP='1_ISOLATED',1,0)) > 0 AND SUM(IFF(GRP<>'1_ISOLATED',1,0)) > 0
), f AS (
  SELECT g.* FROM g JOIN both b ON b.USER_ID=g.USER_ID AND b.D=g.D AND b.COH=g.COH
)
SELECT GRP, COUNT(*) AS TASKS,
  ROUND(SUM(SECS)/COUNT(*),1) AS AHT_S, MEDIAN(SECS) AS AHT_MED_S,
  ROUND(SUM(DRUG_MEAN)/COUNT(*),1) AS EXPECTED_FROM_DRUG_MIX_S,
  ROUND(SUM(SECS)/NULLIF(SUM(DRUG_MEAN),0),4) AS DRUG_ADJ_INDEX
FROM f GROUP BY 1 ORDER BY 1





 WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS BETWEEN 0 and 300
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
    AND USAGE_STATE='APPROVED'
    AND IS_REFILL = FALSE
    AND HANDOFF_TYPE is NULL
), drugbench AS (
  SELECT PART_NUMBER, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base GROUP BY 1
)
select d.*, p.name from  drugbench d
join edldb.pdm.product p on d.part_number = p.part_number
where cnt > 10 order by cnt desc limit 10;



  WITH base AS (
    SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
           DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
           CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
    FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
    WHERE TASK_TYPE='DUR'
      AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
      AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
      -- AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS BETWEEN 0 and 300
      AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
      AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
      AND USAGE_STATE='APPROVED'
      AND IS_REFILL = FALSE
      AND HANDOFF_TYPE is NULL
  ), raw AS (
    SELECT PART_NUMBER, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base GROUP BY 1
  ),
  drugbench as (
  SELECT b.PART_NUMBER, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base b join raw
  d on b.part_number = d.part_number where secs < d.drug_p95
  GROUP BY 1
  )
  select d.*, p.name from  drugbench d
  join edldb.pdm.product p on d.part_number = p.part_number
  where cnt > 10 order by cnt desc limit 10;





-- Truncated


WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
  ), raw AS (
    SELECT PART_NUMBER, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base GROUP BY 1
  ),
  drugbench as (
  SELECT b.PART_NUMBER, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base b join raw
  d on b.part_number = d.part_number where secs < d.drug_p95
  GROUP BY 1
), ded AS (
  SELECT * FROM (SELECT b.*, ROW_NUMBER() OVER
                 (PARTITION BY USER_ID, ORDER_ID ORDER BY STARTED_AT) RN
                 FROM base b join raw r on r.part_number = b.part_number where b.secs < r.drug_p95) WHERE RN = 1
), s AS (
  SELECT *, LAG(COH) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT) AS PCOH FROM ded
), r AS (
  SELECT *, SUM(IFF(PCOH=COH,0,1)) OVER (PARTITION BY USER_ID ORDER BY STARTED_AT
              ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUN_ID
  FROM s
), p AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY USER_ID, RUN_ID ORDER BY STARTED_AT) AS POS,
            COUNT(*)     OVER (PARTITION BY USER_ID, RUN_ID) AS RUN_LEN
  FROM r
), g AS (
  SELECT p.USER_ID, p.D, p.COH, p.SECS, db.DRUG_MEAN,
         CASE WHEN RUN_LEN = 1 THEN '1_ISOLATED'
              WHEN POS = 1 THEN '2_RUN_START'
              WHEN POS = 2 THEN '3_POS_2'
              WHEN POS = 3 THEN '4_POS_3'
              WHEN POS BETWEEN 4 AND 6 THEN '5_POS_4_6'
              ELSE '6_POS_7PLUS' END AS GRP
  FROM p JOIN drugbench db ON db.PART_NUMBER = p.PART_NUMBER
), both AS (
  SELECT USER_ID, D, COH FROM g GROUP BY 1,2,3
  HAVING SUM(IFF(GRP='1_ISOLATED',1,0)) > 0 AND SUM(IFF(GRP<>'1_ISOLATED',1,0)) > 0
), f AS (
  SELECT g.* FROM g JOIN both b ON b.USER_ID=g.USER_ID AND b.D=g.D AND b.COH=g.COH
)
SELECT GRP, COUNT(*) AS TASKS,
  ROUND(SUM(SECS)/COUNT(*),1) AS AHT_S, MEDIAN(SECS) AS AHT_MED_S,
  ROUND(SUM(DRUG_MEAN)/COUNT(*),1) AS EXPECTED_FROM_DRUG_MIX_S,
  ROUND(SUM(SECS)/NULLIF(SUM(DRUG_MEAN),0),4) AS DRUG_ADJ_INDEX
FROM f GROUP BY 1 ORDER BY 1
