WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
    AND USAGE_STATE='APPROVED'
    AND IS_REFILL = FALSE
    AND HANDOFF_TYPE is NULL
    AND PART_NUMBER = 224823
), raw AS (
  SELECT USER_ID, PART_NUMBER, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base GROUP BY 1,2
),
drugbench as (
SELECT b.USER_ID, b.PART_NUMBER, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base b join raw
d on b.part_number = d.part_number  and b.user_id = d.user_id where secs < d.drug_p95
GROUP BY 1,2)
select  * from drugbench d order by  drug_mean asc
limit 20;


WITH base AS (
  SELECT USER_ID, ORDER_ID, PART_NUMBER, STARTED_AT,
         DWELL_IN_PROGRESS_TO_CLOSED_SECONDS AS SECS, ITEM_COHORT AS COH,
         CONVERT_TIMEZONE('UTC', STARTED_AT)::DATE AS D
  FROM EDLDB.PET_HEALTH_ANALYTICS_SANDBOX.FCT__TASKS_LIFECYCLE
  WHERE TASK_TYPE='DUR'
    AND TASK_CREATED_AT >= '2026-02-01' AND TASK_CREATED_AT < '2026-08-01'
    AND DWELL_IN_PROGRESS_TO_CLOSED_SECONDS IS NOT NULL
    AND USER_ID IS NOT NULL AND STARTED_AT IS NOT NULL
    AND PART_NUMBER IS NOT NULL AND ITEM_COHORT IS NOT NULL
    AND USAGE_STATE='APPROVED'
    AND IS_REFILL = FALSE
    AND HANDOFF_TYPE is NULL
    AND ITEM_COHORT = 'Cohort 4'
), raw AS (
  SELECT USER_ID, COH, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base GROUP BY 1,2
),
drugbench as (
SELECT b.USER_ID, b.COH, ROUND(MEDIAN(SECS),2) as DRUG_MEDIAN, AVG(SECS) AS DRUG_MEAN, ROUND(APPROX_PERCENTILE(SECS,0.90),2) AS DRUG_P90,  ROUND(APPROX_PERCENTILE(SECS,0.95),2) AS DRUG_P95, MAX(SECS) AS DRUG_MAX, ROUND(STDDEV(SECS),2)  as DEVIATION, COUNT(*) as cnt FROM base b join raw
d on b.coh = d.coh  and b.user_id = d.user_id where secs < d.drug_p95
GROUP BY 1,2)
select  * from drugbench d order by  drug_mean asc
limit 20;




select d.*, p.name from  drugbench d
join edldb.pdm.product p on d.part_number = p.part_number
where cnt > 10 order by cnt desc limit 10;
